const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const REGISTER = "REGISTER";
const UPLOADING = "UPLOADING";
const UPLOADED = "UPLOADED";
const UPLOAD_PROGRESS = "UPLOAD PROGRESS";

export {
    LOGIN,
    LOGOUT,
    REGISTER,
    UPLOADING,
    UPLOADED,
    UPLOAD_PROGRESS
}