const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const REGISTER = "REGISTER";
const UPLOADING = "UPLOADING";
const UPLOADED = "UPLOADED";

export {
    LOGIN,
    LOGOUT,
    REGISTER,
    UPLOADING,
    UPLOADED,
}