const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const REGISTER = "REGISTER";
const UPLOADING = "UPLOADING";
const UPLOADED = "UPLOADED";
const UPLOAD_PROGRESS = "UPLOAD PROGRESS";
const SET_USER_INFO = "SET USER INFORMATION";
const SET_USERNAME = "SET USER NAME";
const SET_USER_AVATAR = "SET USER AVATAR";
const SET_USERID = "SET USERID";

export {
    LOGIN,
    LOGOUT,
    REGISTER,
    UPLOADING,
    UPLOADED,
    UPLOAD_PROGRESS,
    SET_USER_INFO,
    SET_USERNAME,
    SET_USER_AVATAR,
    SET_USERID
}