const SENT_MAIL = "SENT EMAIL";
const ERROR = "ERROR"; 
const EMAIL_ALREADY_EXISTS = "EMAIL ALREADY EXISTS";
const INVALID_EMAIL = "INVALID EMAIL ADDRESS";
const ACCEPT = "ACCEPT";
const INVALID_PASSWORD = "INVALID PASSWORD";

export {
    SENT_MAIL,
    ERROR,
    EMAIL_ALREADY_EXISTS,
    INVALID_EMAIL,
    ACCEPT,
    INVALID_PASSWORD
}