const SENT_MAIL = "SENT MAIL";
const ERROR = "ERROR"; 
const EMAIL_ALREADY_EXISTS = "EMAIL ALREADY EXISTS";
const INVALID_EMAIL = "INVALID EMAIL ADDRESS";

export {
    SENT_MAIL,
    ERROR,
    EMAIL_ALREADY_EXISTS,
    INVALID_EMAIL
}